### ISSUE TITLE
Error on last_words module

### ISSUE THREAD

**Issue by GhislainC** [pipoteam/pipobot-modules#16]
When a user speaks for the first time, pipobot raises an error (see below).

    OperationalError: (OperationalError) (1048, "Column 'created' cannot be null") 'INSERT INTO last_words (kuid, message, created) VALUES (%s, %s, %s)' (91L, "toto", None)

An existing workaround is to create the entry on database with a timestamp (`0000-00-00 00:00:00` for example). Then, when the user speak again, pipobot will juste update the timestamp and the message.

In brief : 
Create entry on `last_words` table is not possible due to a null timestamp on `created` column.
Update an entry is still possible.

**Comment by sleduc** [comment]
That is strange, I do not seem to reproduce this issue.
I tried to reproduce this with the head of pipobot-modules but it seems to work correctly and the entry is correctly added to the database.

The only think I could reproduced was when I had entries in my database from a previous version of pipobot-modules (before commit 7ae196c0afd69f5084ed5eafa4c2617f048b8e37), then updating and speaking lead to the following exception : 

> 2016-09-11 16:17:50,567 - pipobot.lib.modules - ERROR - Error from module <class 'last_words.LastWordsModule'> : Traceback (most recent call last):
>   File "pipobot/lib/modules.py", line 84, in do_answer
>     send = self.answer(sender, msg_body)
>   File "../pipobot-modules/last_words/__init__.py", line 18, in answer
>     last_words = self.bot.session.query(LastWords).filter(LastWords.kuid == user.kuid).first()
>   File "/home/seb/.virtualenvs/pipobot2/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2334, in first
>     ret = list(self[0:1])
>   File "/home/seb/.virtualenvs/pipobot2/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2201, in __getitem__
>     return list(res)
>   File "/home/seb/.virtualenvs/pipobot2/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2405, in __iter__
>     return self._execute_and_instances(context)
>   File "/home/seb/.virtualenvs/pipobot2/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2420, in _execute_and_instances
>     result = conn.execute(querycontext.statement, self._params)
>   File "/home/seb/.virtualenvs/pipobot2/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 727, in execute
>     return meth(self, multiparams, params)
>   File "/home/seb/.virtualenvs/pipobot2/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 322, in _execute_on_connection
>     return connection._execute_clauseelement(self, multiparams, params)
>   File "/home/seb/.virtualenvs/pipobot2/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 824, in _execute_clauseelement
>     compiled_sql, distilled_params
>   File "/home/seb/.virtualenvs/pipobot2/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 954, in _execute_context
>     context)
>   File "/home/seb/.virtualenvs/pipobot2/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1116, in _handle_dbapi_exception
>     exc_info
>   File "/home/seb/.virtualenvs/pipobot2/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 189, in raise_from_cause
>     reraise(type(exception), exception, tb=exc_tb)
>   File "/home/seb/.virtualenvs/pipobot2/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 947, in _execute_context
>     context)
>   File "/home/seb/.virtualenvs/pipobot2/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 435, in do_execute
>     cursor.execute(statement, parameters)
> OperationalError: (OperationalError) no such column: last_words.created u'SELECT last_words.kuid AS last_words_kuid, last_words.message AS last_words_message, last_words.created AS last_words_created \nFROM last_words \nWHERE last_words.kuid = ?\n LIMIT ? OFFSET ?' (1, 1, 0)

A simple update of the database fixed the problem : 
``alter table last_words add column created DATETIME;``

Unless this is a different issue that I reproduced....
How did you reproduce this exactly ? 
Are you with the head of pipobot/pipobot-modules ?
What version of sqlalchemy are you using, with which database backend ?

**Comment by nim65s** [comment]
sqlalchemy 0.9.8 & MySQL.
I did not saw your solution, and dropped the table and re created it again. And now, it works :)
